version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./code:/var/www/html
    command: ["sh", "-c", "chown -R www-data:www-data /var/www/html && php-fpm"]
    