<?php 
/*
 * ShipcloudAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ShipcloudAPIV1Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CreatingAShipmentResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @maps carrier_tracking_no
     * @var string $carrierTrackingNo public property
     */
    public $carrierTrackingNo;

    /**
     * @todo Write general description for this property
     * @required
     * @maps tracking_url
     * @var string $trackingUrl public property
     */
    public $trackingUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @maps label_url
     * @var string $labelUrl public property
     */
    public $labelUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $price public property
     */
    public $price;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $id                    Initialization value for the property $this->id                 
     * @param   string            $carrierTrackingNo     Initialization value for the property $this->carrierTrackingNo  
     * @param   string            $trackingUrl           Initialization value for the property $this->trackingUrl        
     * @param   string            $labelUrl              Initialization value for the property $this->labelUrl           
     * @param   double            $price                 Initialization value for the property $this->price              
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->id                  = func_get_arg(0);
            $this->carrierTrackingNo   = func_get_arg(1);
            $this->trackingUrl         = func_get_arg(2);
            $this->labelUrl            = func_get_arg(3);
            $this->price               = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                  = $this->id;
        $json['carrier_tracking_no'] = $this->carrierTrackingNo;
        $json['tracking_url']        = $this->trackingUrl;
        $json['label_url']           = $this->labelUrl;
        $json['price']               = $this->price;

        return $json;
    }
}