<?php

defined('_VALID_CALL') or die('Direct Access is not allowed.');

if($cgID == 101)
{
    /**
     *
     **** KLARNA_CONFIG_KP_BASIC
    _KLARNA_CONFIG_KP_MID_TEST
    _KLARNA_CONFIG_KP_PWD_TEST
    _KLARNA_CONFIG_KP_TESTMODE
    _KLARNA_CONFIG_KP_MID
    _KLARNA_CONFIG_KP_PWD
    _KLARNA_CONFIG_KP_TESTMODE_CUSTOMER_GROUP
     *
     **** KLARNA_CONFIG_ADVANCED
    _KLARNA_CONFIG_SEND_EXTENDED_PRODUCT_INFO
     *
     **** KLARNA_CONFIG_LAYOUT
    _KLARNA_CONFIG_LOGO_DESIGN
    _KLARNA_CONFIG_WIDGET_DESIGN
    _KLARNA_CONFIG_KP_RADIUS_BORDER
    _KLARNA_CONFIG_KP_COLOR_BORDER
    _KLARNA_CONFIG_KP_COLOR_BORDER_SELECTED
    _KLARNA_CONFIG_KP_COLOR_BUTTON
    _KLARNA_CONFIG_KP_COLOR_BUTTON_TEXT
    _KLARNA_CONFIG_KP_COLOR_CHECKBOX
    _KLARNA_CONFIG_KP_COLOR_CHECKBOX_CHECKMARK
    _KLARNA_CONFIG_KP_COLOR_DETAILS
    _KLARNA_CONFIG_KP_COLOR_HEADER
    _KLARNA_CONFIG_KP_COLOR_LINK
    _KLARNA_CONFIG_KP_COLOR_TEXT
    _KLARNA_CONFIG_KP_COLOR_TEXT_SECONDARY
     *
     **** KLARNA_CONFIG_STATUS_MAPPING
    _KLARNA_CONFIG_STATUS_ACCEPTED
    _KLARNA_CONFIG_STATUS_PENDING
    _KLARNA_CONFIG_STATUS_REJECTED
    _KLARNA_CONFIG_STATUS_CANCELED
     *
     **** KLARNA_CONFIG_TRIGGER
    _KLARNA_CONFIG_TRIGGER_FULL_CAPTURE
    _KLARNA_CONFIG_TRIGGER_FULL_CAPTURE_FORCE_STATUS_UPDATE
    _KLARNA_CONFIG_TRIGGER_CANCEL
    _KLARNA_CONFIG_TRIGGER_CANCEL_FORCE_STATUS_UPDATE
    _KLARNA_CONFIG_TRIGGER_ESCALATION_EMAIL
    _KLARNA_CONFIG_TRIGGER_ALLOWED_TRIGGER
     */

    $klarna_groupings = array(
        'KLARNA_CONFIG_KP_BASIC' => array(
            '_KLARNA_CONFIG_KP_MID_TEST',
            '_KLARNA_CONFIG_KP_PWD_TEST',
            '_KLARNA_CONFIG_KP_TESTMODE',
            '_KLARNA_CONFIG_KP_MID',
            '_KLARNA_CONFIG_KP_PWD',
            '_KLARNA_CONFIG_KP_TESTMODE_CUSTOMER_GROUP'
        ),
        'KLARNA_CONFIG_ADVANCED' => array(
            '_KLARNA_CONFIG_KP_PAYMENT_METHODS',
            '_KLARNA_CONFIG_SEND_EXTENDED_PRODUCT_INFO',
            '_KLARNA_CONFIG_KP_B2B_GROUPS',
            '_KLARNA_CONFIG_KP_B2B_ENABLED',
            '_KLARNA_CONFIG_KP_B2B_INFO',

            // hidden status stuff. to prevent tab 'Standard'
            '_KLARNA_CONFIG_ACCOUNT_STATUS',
            '_KLARNA_CONFIG_ACCOUNT_REASON',
            '_KLARNA_CONFIG_ACCOUNT_TYPE'
        ),
        'KLARNA_CONFIG_STATUS_MAPPING' => array(
            '_KLARNA_CONFIG_STATUS_ACCEPTED',
            '_KLARNA_CONFIG_STATUS_PENDING',
            '_KLARNA_CONFIG_STATUS_REJECTED',
            '_KLARNA_CONFIG_STATUS_CANCELED',
        ),
        'KLARNA_CONFIG_TRIGGER' => array(
            '_KLARNA_CONFIG_TRIGGER_FULL_CAPTURE',
            '_KLARNA_CONFIG_TRIGGER_FULL_CAPTURE_FORCE_STATUS_UPDATE',
            '_KLARNA_CONFIG_TRIGGER_CANCEL',
            '_KLARNA_CONFIG_TRIGGER_CANCEL_FORCE_STATUS_UPDATE',
            '_KLARNA_CONFIG_TRIGGER_ESCALATION_EMAIL',
            '_KLARNA_CONFIG_TRIGGER_ALLOWED_TRIGGER'
        ),
        'KLARNA_CONFIG_KP_LAYOUT' => array(

            '_KLARNA_CONFIG_KP_LOGO_DESIGN',
            '_KLARNA_CONFIG_WIDGET_DESIGN',

            '_KLARNA_CONFIG_KP_RADIUS_BORDER',
            '_KLARNA_CONFIG_KP_COLOR_BORDER',
            '_KLARNA_CONFIG_KP_COLOR_BORDER_SELECTED',

            '_KLARNA_CONFIG_KP_COLOR_BUTTON',
            '_KLARNA_CONFIG_KP_COLOR_BUTTON_TEXT',

            '_KLARNA_CONFIG_KP_COLOR_CHECKBOX',
            '_KLARNA_CONFIG_KP_COLOR_CHECKBOX_CHECKMARK',

            '_KLARNA_CONFIG_KP_COLOR_DETAILS',
            '_KLARNA_CONFIG_KP_COLOR_HEADER',
            '_KLARNA_CONFIG_KP_COLOR_LINK',
            '_KLARNA_CONFIG_KP_COLOR_TEXT',
            '_KLARNA_CONFIG_KP_COLOR_TEXT_SECONDARY',
            
        ),
        /*
        'KLARNA_CONFIG_KP_B2B' => array(
            '_KLARNA_CONFIG_KP_B2B_ENABLED',

        )
        */
    );

    foreach($klarna_groupings as $klarna_group => $items)
    {
        foreach ($items as $item)
        {
            $grouping[$item] = array('position' => $klarna_group);
        }
    }
}

