<?php 
/*
 * ShipcloudAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ShipcloudAPIV1Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class UpdatingAShipmentRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var object $to public property
     */
    public $to;

    /**
     * @todo Write general description for this property
     * @required
     * @var object $package public property
     */
    public $package;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $carrier public property
     */
    public $carrier;

    /**
     * @todo Write general description for this property
     * @required
     * @maps reference_number
     * @var string $referenceNumber public property
     */
    public $referenceNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @maps create_shipping_label
     * @var bool $createShippingLabel public property
     */
    public $createShippingLabel;

    /**
     * Constructor to set initial or default values of member properties
     * @param   object            $to                      Initialization value for the property $this->to                   
     * @param   object            $package                 Initialization value for the property $this->package              
     * @param   string            $carrier                 Initialization value for the property $this->carrier              
     * @param   string            $referenceNumber         Initialization value for the property $this->referenceNumber      
     * @param   bool              $createShippingLabel     Initialization value for the property $this->createShippingLabel  
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->to                    = func_get_arg(0);
            $this->package               = func_get_arg(1);
            $this->carrier               = func_get_arg(2);
            $this->referenceNumber       = func_get_arg(3);
            $this->createShippingLabel   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['to']                    = $this->to;
        $json['package']               = $this->package;
        $json['carrier']               = $this->carrier;
        $json['reference_number']      = $this->referenceNumber;
        $json['create_shipping_label'] = $this->createShippingLabel;

        return $json;
    }
}